packages:
  - packages/*
  - demo

catalogs:
  default:
    '@tsconfig/node24': ^24.0.4
    '@types/node': ^25.0.10
    '@vitejs/plugin-vue': ^6.0.3
    '@vitest/coverage-v8': 4.0.18
    '@vue/devtools-api': ^8.0.5
    '@vue/tsconfig': ^0.8.1
    oxfmt: ^0.27.0
    oxlint: ^1.42.0
    pinia: ^3.0.4
    tsdown: ^0.20.1
    typescript: ^5.9.3
    vite: beta
    vite-plugin-vue-devtools: ^8.0.5
    vitest: ^4.0.18
    vue: ^3.5.0
    vue-tsc: ^3.2.2

linkWorkspacePackages: true
